### ISSUE TITLE
Gource in GitHub Actions

### ISSUE THREAD

**Issue by NBprojekt** [acaudwell/Gource#239]
Im trying to get gource running in my GitHub Action.   
But it always fails with the this error code:

``` console
/home/runner/work/_temp/b6f78dd3-fcab-415c-b39d-df167dc2440a.sh: line 13:  5981 Segmentation fault      (core dumped) gource -1280x720 --seconds-per-day .9 --auto-skip-seconds .01 --multi-sampling --stop-at-end --highlight-users --camera-mode overview --hide mouse,filenames --key --file-idle-time 0 --max-files 0 --background-colour 24292e --title "App" -o gource.ppm .
```

Is that a bug in gource? 
If not any hints where I can find a solution?

<details>
  <summary> Also here is my `yml` file </summary>
  
```yml
name: Gource
on:
  push:
    branches:
      - master
    
jobs:
  Gource:
    name: Create and uplaod gource video
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gource ffmpeg
    - name: Create gource ppm
      run: |
        gource --seconds-per-day .9 \
               --auto-skip-seconds .01 \
               --multi-sampling \
               --stop-at-end \
               --highlight-users \
               --camera-mode overview \
               --hide mouse,filenames \
               --key --file-idle-time 0 \
               --max-files 0 \
               --background-colour 24292e \
               --title "App" \
               -1280x720\
               -o gource.ppm .
    - name: Minify gource ppm
      run: |
        ffmpeg -y -r 60 -f image2pipe \
               -vcodec ppm -i gource.ppm \
               -vcodec libx264  \
               -preset medium \
               -pix_fmt yuv420p \
               -crf 1 -threads 0 \
               -bf 0 app.mp4
    - name: Upload gource pm4
      uses: actions/upload-artifact@v2
      with:
        path: ./app.mp4
```
</details>
